### PR TITLE
[OpenShift] fixes the disable affinity assistant configuration

### LINKED ISSUE #372: AffinityAssistant configuration on OpenShift not taken into account
# Expected Behavior

Changing the TektonPipeline configuration `disable-affinity-assistant` to `false` is taken into account under OpenShift and the affinity assistant is enabled.

# Actual Behavior

Changing the TektonPipeline configuration `disable-affinity-assistant` to `false` is not taken into account, it is forced to `true` by the controller (see [here](https://github.com/tektoncd/operator/blob/main/pkg/reconciler/openshift/tektonpipeline/extension.go#L141))

# Steps to Reproduce the Problem

1. Install the operator
2. Update the `TektonPipeline` CR
3. Look at the `openshift/pipelines` `feature-flags` configmap.

/cc @nikhil-thomas @sm43 to correct me if I am saying something wrong

### PR DESCRIPTION
**Pull request by sm43**
This is always true in case of openshift due to which user would
not able to enable it. so this fixes by removing the defaulting in
Operator CR and adding the field only when user adds it.
By default, the value in configmap is false for kubernetes and will
be changed to true for openshift which user can change if requires.

fixes #372 

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

File: pkg/reconciler/openshift/tektonpipeline/extension.go [hunk 1]
```diff
@@ -135,10 +136,10 @@ func SetDefault(properties *v1alpha1.PipelineProperties) bool {
 		updated = true
 	}
 
-	// Set `disable-affinity-assistant` to true
-	// webhook will set `false` as default value
-	if properties.DisableAffinityAssistant == nil || !*properties.DisableAffinityAssistant {
-		*properties.DisableAffinityAssistant = DefaultDisableAffinityAssistant
+	// Set `disable-affinity-assistant` to true if not set in CR
+	// webhook will not set any value but by default in pipelines configmap it will be false
+	if properties.DisableAffinityAssistant == nil {
```
Comment (savitaashture) [inline pkg/reconciler/openshift/tektonpipeline/extension.go:141]: so from Operator we can configure `DisableAffinityAssistant` only for Openshift and not for K8s then in that case can we add comment here https://github.com/tektoncd/operator/blob/main/pkg/apis/operator/v1alpha1/tektonpipeline_types.go#L84 so that it will be more clear

not necessarily in this instead we do it in another PR

WDYT?

Comment (vdemeester) [reply pkg/reconciler/openshift/tektonpipeline/extension.go:141]: @savitaashture it's support on all platform. Only on Openshift the default is different (`true` instead of `false`)

Comment (sm43) [reply pkg/reconciler/openshift/tektonpipeline/extension.go:141]: yep. on kubernetes by default the field will not be set in TektonConfig CR, user can define and alter value.
by default it will be false in configmap.

Comment (vdemeester) [reply pkg/reconciler/openshift/tektonpipeline/extension.go:141]: @sm43 but on k8s, if the user set then in the `TektonConfig` CR, the will be applied to the managed tekton instance right ?

Comment (sm43) [reply pkg/reconciler/openshift/tektonpipeline/extension.go:141]: yes.. user can define the field in k8s and change the value. there is no behavior change

**Comment by savitaashture** [comment]
/lgtm

/hold 
For others to take look

**Review by vdemeester — APPROVED** [review]
