### PR TITLE
Fix TektonResult CR not showing version

### LINKED ISSUE #1719: External DB option doesn't filter DB resources during creation time
# Expected Behavior
The external DB option should filter DB resources during creation time.
# Actual Behavior
The external DB option doesn't filter DB resources during creation time

If an internal DB is created and afterward,  we use the external DB option,  db resources are filtered out. But not when we do during creation time.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

### PR DESCRIPTION
**Pull request by khrm**
Fix TektonResult CR version for `kubectl get TektonResult` and also fixes result's external db filter during creation time.

Fixes #1719 #1717
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/assign @savitaashture @jkandasa

File: pkg/reconciler/common/initcontroller.go [hunk 1]
```diff
@@ -112,7 +112,7 @@ func (ctrl Controller) fetchSourceManifests(ctx context.Context, opts PayloadOpt
 	case "chains":
 		var chain v1alpha1.TektonChain
 		return AppendTarget(ctx, ctrl.Manifest, &chain)
-	case "results":
+	case "tekton-results":
```
Comment (PuneetPunamiya) [inline pkg/reconciler/common/initcontroller.go:115]: Why do we need to change this ?

Comment (khrm) [reply pkg/reconciler/common/initcontroller.go:115]: This is wrong because configmapInfo for results is tekton-results instead of results like for other components.

**Review by jkandasa — APPROVED** [review]

**Comment by PuneetPunamiya** [comment]
LGTM
