### PR TITLE
Fix filter and Transform for TektonResult

### LINKED ISSUE #2023: TektonResult installaiton fails if targerNamespace is different
# Expected Behavior
Tekton Result should installed and we should get:
```
 oc get TektonResult result -w
result   v0.9.1    True      
```
# Actual Behavior
Installation fails and we get:
```
 oc get TektonResult result -w
NAME     VERSION   READY   REASON
result   v0.9.1    False   Installer set not ready: Install failed with message: namespaces "tekton-pipelines" not found
```

# Steps to Reproduce the Problem

1. Install v0.70 operator
2. Instal TektonResult CR.

### PR DESCRIPTION
**Pull request by khrm**
Filter was changing the reference for Transformer which led to an incorrect manifest (the one without any transformation but only filter) being applied.

Fix #2023

* This issue introduced in #2003 and hope this PR fixes that

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

File: pkg/reconciler/kubernetes/tektonresult/filter.go [hunk 1]
```diff
@@ -26,11 +26,12 @@ const (
...
-func filterExternalDB(tr *v1alpha1.TektonResult, manifest mf.Manifest) *mf.Manifest {
+func filterExternalDB(tr *v1alpha1.TektonResult, inputMf *mf.Manifest) {
+	manifest := *inputMf
 	if tr.Spec.IsExternalDB {
 		manifest = manifest.Filter(mf.Not(mf.All(mf.ByKind("StatefulSet"), mf.ByName(statefulSetDB))))
 		manifest = manifest.Filter(mf.Not(mf.All(mf.ByKind("ConfigMap"), mf.ByName(configPostgresDB))))
 		manifest = manifest.Filter(mf.Not(mf.All(mf.ByKind("Service"), mf.ByName(servicePostgresDB))))
 	}
-	return &manifest
+	*inputMf = manifest
```
Comment (savitaashture) [inline pkg/reconciler/kubernetes/tektonresult/filter.go:36]: How about this  :thinking: 
```
func filterExternalDB(tr *v1alpha1.TektonResult, inputMf *mf.Manifest) {
	if tr.Spec.IsExternalDB {
		*inputMf = inputMf.Filter(mf.Not(mf.All(mf.ByKind("StatefulSet"), mf.ByName(statefulSetDB))))
		*inputMf = inputMf.Filter(mf.Not(mf.All(mf.ByKind("ConfigMap"), mf.ByName(configPostgresDB))))
		*inputMf = inputMf.Filter(mf.Not(mf.All(mf.ByKind("Service"), mf.ByName(servicePostgresDB))))
	}
}
```

Comment (khrm) [reply pkg/reconciler/kubernetes/tektonresult/filter.go]: Yes, that's more concise.

**Comment by savitaashture** [comment]
Verification
* locally installed operator release-v0.69.x branch
* Followed https://docs.openshift.com/pipelines/1.12/records/using-tekton-results-for-openshift-pipelines-observability.html to install results
* Upgraded by installing from this branch https://github.com/khrm/operator/tree/filterRef
* Verified results pods are running  state
```
tekton-results-api-5bfd8b4cc8-trlpd                  1/1     Running   0          89s
tekton-results-postgres-0                            1/1     Running   0          2m46s
tekton-results-watcher-6dfc9d789b-6b27b              1/1     Running   0          89s
```

**Review by vdemeester — APPROVED** [review]
