### PR TITLE
Fix Conflict between Results PreReconciler and Reconciler

### LINKED ISSUE #2010: Resolve conflict between Prereonciler and Reconciler during upgrade
# Expected Behavior
Upgrade from one version to another should happen in all scenarios.
# Actual Behavior
At present, if the result was installed, then the previous release fails in OpenShift. We have to delete tektoninstallerset of results to proceed. This is because the reconciler and older release reconciler have similar manifests. 
# Steps to Reproduce the Problem

1. Install older release in OpenShift
2. Install Tekton Result
3. Upgrade operator.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

### PR DESCRIPTION
**Pull request by khrm**
This fixes conflict between prereconciler and reconciler during operator upgrade.
Fixes #2010 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Run `make test lint` before submitting a PR
- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind bug

**Review by jkandasa — APPROVED** [review]

File: pkg/reconciler/kubernetes/tektonresult/tektonresult.go [hunk 1]
```diff
@@ -147,6 +147,10 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, tr *v1alpha1.TektonResul
 	}
 	tr.Status.MarkDependenciesInstalled()
 
+	// This function needs to be removed in the next release of operator.
+	if err := r.conflictTIS(ctx); err != nil {
```
Comment (piyush-garg) [inline pkg/reconciler/kubernetes/tektonresult/tektonresult.go:151]: why we need to do this before preReconcile?

File: pkg/reconciler/kubernetes/tektonresult/tektonresult.go [hunk 2]
```diff
@@ -298,6 +302,59 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, tr *v1alpha1.TektonResul
 	return nil
 }
 
+// This function exists to resolve conflict between PreReconciler and Reconciler Installerset.
```
Comment (piyush-garg) [inline pkg/reconciler/kubernetes/tektonresult/tektonresult.go:305]: What is the conflict?

File: pkg/reconciler/kubernetes/tektonresult/tektonresult.go [hunk 3]
```diff
@@ -298,6 +302,59 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, tr *v1alpha1.TektonResul
...
+		Get(ctx, existingInstallerSet, metav1.GetOptions{})
+	if err != nil {
+		if apierrors.IsNotFound(err) {
+			return nil
+		}
+		logger.Error("failed to get InstallerSet: %s", err)
+		return err
+	}
+
+	installerSetReleaseVersion := installedTIS.Labels[v1alpha1.ReleaseVersionKey]
```
[the remark this answers is not in the document]
Comment (khrm) [reply pkg/reconciler/kubernetes/tektonresult/tektonresult.go:334]: Yes, we do this. But in this release, we are doing before pre reconcile.

File: pkg/reconciler/kubernetes/tektonresult/tektonresult.go (hunk 2 above)
Comment (khrm) [reply pkg/reconciler/kubernetes/tektonresult/tektonresult.go:305]: Both have db manifest. But we don't need this manifest.

File: pkg/reconciler/kubernetes/tektonresult/tektonresult.go (hunk 1 above)
Comment (khrm) [reply pkg/reconciler/kubernetes/tektonresult/tektonresult.go:151]: To remove manifest which are common in installerset and pre-installerset.

Comment (khrm) [reply pkg/reconciler/kubernetes/tektonresult/tektonresult.go:151]: From next release, there won't be anything common in between installerset and pre-installerset.

**Comment by khrm** [comment]
I think there's some problem with the tide setup. I didn't resolve any merge conflict and it was asking for a rebase.
