### PR TITLE
Ensure the configured `TargetNamespace` overrides the default namespace in the Dashboard's container args

### LINKED ISSUE #2438: Tekton operator | Custom namespace deployment issue
# Expected Behavior

Successful deployment of all resources with everything working out of the box.

image

# Actual Behavior

Tekton dashboard cannot fetch the configmaps that contain the versions of the tekton components. Most likely due to a role or role binding issue that happens when you customize the `defaultTargetNamespace` value in the helm chart.

If you don't specify a custom namespace and let the operator deploy everything in the default `tekton-pipelines` namespace the issue is not present!

# Steps to Reproduce the Problem

1. Deploy Tekton Operator (tekton-operator-0.74.0) via HELM using the values.yaml [values.yaml.txt](https://github.com/user-attachments/files/18005694/values.yaml.txt)
2. Wait for the operator to finish with deployment
3. Create an ingress for the Tekton Dashboard and notice the errors

image
image

Raw Error:

```
{"level":"error","ts":1733306990.525748,"caller":"endpoints/dashboard.go:27","msg":"Error getting the Tekton triggers info ConfigMap: configmaps \"triggers-info\" is forbidden: User \"system:serviceaccount:mmp-pipelines:tekton-dashboard\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"tekton-pipelines\"","stacktrace":"github.com/tektoncd/dashboard/pkg/endpoints.getVersion\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/dashboard.go:27\ngithub.com/tektoncd/dashboard/pkg/endpoints.getTriggersVersion\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/dashboard.go:56\ngithub.com/tektoncd/dashboard/pkg/endpoints.IsTriggersInstalled\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/dashboard.go:67\ngithub.com/tektoncd/dashboard/pkg/endpoints.Resource.GetProperties\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/cluster.go:64\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2166\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2683\ngithub.com/tektoncd/dashboard/pkg/csrf.(*csrf).ServeHTTP\n\tgithub.com/tektoncd/dashboard/pkg/csrf/csrf.go:74\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3137\nnet/http.(*conn).serve\n\tnet/http/server.go:2039"}

{"level":"error","ts":1733306923.1582959,"caller":"endpoints/dashboard.go:27","msg":"Error getting the Tekton pipelines info ConfigMap: configmaps \"pipelines-info\" is forbidden: User \"system:serviceaccount:mmp-pipelines:tekton-dashboard\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"tekton-pipelines\"","stacktrace":"github.com/tektoncd/dashboard/pkg/endpoints.getVersion\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/dashboard.go:27\ngithub.com/tektoncd/dashboard/pkg/endpoints.getPipelineVersion\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/dashboard.go:46\ngithub.com/tektoncd/dashboard/pkg/endpoints.Resource.GetProperties\n\tgithub.com/tektoncd/dashboard/pkg/endpoints/cluster.go:46\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2166\nnet/http.(*ServeMux).ServeHTTP\n\tnet/http/server.go:2683\ngithub.com/tektoncd/dashboard/pkg/csrf.(*csrf).ServeHTTP\n\tgithub.com/tektoncd/dashboard/pkg/csrf/csrf.go:74\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:3137\nnet/http.(*conn).serve\n\tnet/http/server.go:2039"}
```

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**
  ```
  Client Version: v1.30.6
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.30.6
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

  ```v0.65.2```

Plain vanilla k8s, deployed via Kubespray on Ubuntu Server 24.04.1 LTS

### PR DESCRIPTION
**Pull request by aThorp96**
# Changes

Fixes #2438 

- Remove `results` specific details from the common transformer code
- Ensure the configured `TargetNamespace`  overrides the default namespace in the Dashboard's container args

I've tested this locally and confirmed that the Operator created a deployment for the Dashboard with the correct namespace override per the workflow described in #2438 , however it would be good to have someone test and verify the effect on their end as well

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Run `make test lint` before submitting a PR
- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/operator/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

```release-note
When `defaultTargetNamespace` is specified in the Tekton Config, the value will now override the Dashboard's container args `--pipelines-namespace` and `--triggers-namespace`.
```

### CODE REVIEW

File: pkg/reconciler/common/transformers.go [hunk 1]
```diff
@@ -51,12 +51,11 @@ const (
 	HubImagePrefix                = "IMAGE_HUB_"
 	DashboardImagePrefix          = "IMAGE_DASHBOARD_"
 
+	DefaultPipelinesNamespace = "tekton-pipelines"
```
Comment (pratap0007) [inline pkg/reconciler/common/transformers.go:54]:
```suggestion
	DefaultTargetNamespace = "tekton-pipelines"
```

File: pkg/reconciler/kubernetes/tektondashboard/reconcile.go [hunk 2]
```diff
@@ -113,6 +113,7 @@ func (r *Reconciler) ReconcileKind(ctx context.Context, td *v1alpha1.TektonDashb
 	// and hence deleting the component in the integration tests, targetNamespace was getting deleted. Hence
 	// filtering out the namespace here
 	manifest = manifest.Filter(mf.Not(mf.ByKind("Namespace")))
+
```
Comment (pratap0007) [inline pkg/reconciler/kubernetes/tektondashboard/reconcile.go:116]: can we revert this change?

File: pkg/reconciler/common/transformers.go (hunk 1 above)
Comment (aThorp96) [reply pkg/reconciler/common/transformers.go]: Good call. Changed.

**Comment by pratap0007** [comment]
LGTM

File: pkg/reconciler/kubernetes/tektonresult/transform.go [hunk 3]
```diff
@@ -55,9 +55,13 @@ const (
 	loggingForwarderDelayDuration = "LOGGING_PLUGIN_FORWARDER_DELAY_DURATION"
 	logsAPIKey                    = "LOGS_API"
 	logsTypeKey                   = "LOGS_TYPE"
+
+	resultAPIDeployment     = "tekton-results-api"
+	resultWatcherDeployment = "tekton-results-watcher"
```
Comment (PuneetPunamiya) [inline pkg/reconciler/kubernetes/tektonresult/transform.go:60]: What if a new deployment is added to results component 🤔

Comment (aThorp96) [reply pkg/reconciler/kubernetes/tektonresult/transform.go:60]: In the previous implementation the new deployment name would need to have been added to `pkg/reconciler/common/transformers.go`'s [list of `results` deployments](https://github.com/tektoncd/operator/blob/c77fd642deb2f69c624c66f3e2f4ead8f1dce81f/pkg/reconciler/common/transformers.go#L58) and to [the check](https://github.com/tektoncd/operator/blob/c77fd642deb2f69c624c66f3e2f4ead8f1dce81f/pkg/reconciler/common/transformers.go#L491) in `ReplaceNamespaceInDeploymentEnv` and `ReplaceNamespaceInDeploymentArgs`. 

In this new implementation, the new deployment name would be added here and the the array `resultDeploymentNames` on [line 64](https://github.com/tektoncd/operator/pull/2542/files/e050a9172be149a2c1916726c8858c4362b2944d#diff-75f9ef7e65d67d81f17ba1a762c815f827b0d082c48d7e35326f9c4579f40afbR64)

Comment (PuneetPunamiya) [reply pkg/reconciler/kubernetes/tektonresult/transform.go:60]: Yeah make sense

**Comment by aThorp96** [comment]
@PuneetPunamiya for some reason prow didn't seem to respond to your `/lgtm` or @jkhelil's `/approve` 🤔 

Is anything else required here or was this just a blip in prow?
